/** @type {import('next').NextConfig} */
const nextConfig = {
  async redirects() {
    return [
      { source: "/products", destination: "/product", permanent: true },
      { source: "/products/:path*", destination: "/product/:path*", permanent: true },
      { source: "/vision-2030", destination: "/vision", permanent: true },
      { source: "/ecosystem", destination: "/toto-ecosystem", permanent: true },
      { source: "/rare-earth-mineral", destination: "/rare-earth", permanent: true },
      { source: "/blog", destination: "/insights", permanent: true },
      { source: "/blog/:slug*", destination: "/insights/:slug*", permanent: true },
      { source: "/blogs", destination: "/insights", permanent: true },
      { source: "/blogs/:slug*", destination: "/insights/:slug*", permanent: true },
      { source: "/privacy-policy", destination: "/toto-privacy-policy", permanent: true },
      { source: "/terms-and-condition", destination: "/toto-terms-and-condition", permanent: true },
      { source: "/terms-and-conditions", destination: "/toto-terms-and-condition", permanent: true },
      { source: "/doc-imprint", destination: "/docs", permanent: true },
      { source: "/tokenized-gold", destination: "/tokenized-gold-assets", permanent: true },
      { source: "/tokenized-gold/:path*", destination: "/tokenized-gold-assets/:path*", permanent: true },
      { source: "/tokenized-silver", destination: "/tokenized-silver-assets", permanent: true },
      { source: "/tokenized-silver/:path*", destination: "/tokenized-silver-assets/:path*", permanent: true },
      { source: "/tokenized-platinum", destination: "/tokenized-platinum-assets", permanent: true },
      { source: "/tokenized-platinum/:path*", destination: "/tokenized-platinum-assets/:path*", permanent: true },
      { source: "/tokenized-diamonds", destination: "/tokenized-diamond-assets", permanent: true },
      { source: "/tokenized-diamonds/:path*", destination: "/tokenized-diamond-assets/:path*", permanent: true },
      { source: "/tokenized-diamonds-assets", destination: "/tokenized-diamond-assets", permanent: true },
      { source: "/tokenized-diamonds-assets/:path*", destination: "/tokenized-diamond-assets/:path*", permanent: true },
      { source: "/tokenized-sapphire", destination: "/tokenized-sapphire-assets", permanent: true },
      { source: "/tokenized-sapphire/:path*", destination: "/tokenized-sapphire-assets/:path*", permanent: true },
      { source: "/tokenized-copper", destination: "/tokenized-copper-assets", permanent: true },
      { source: "/tokenized-copper/:path*", destination: "/tokenized-copper-assets/:path*", permanent: true },
      { source: "/tokenized-tin", destination: "/tokenized-tin-assets", permanent: true },
      { source: "/tokenized-tin/:path*", destination: "/tokenized-tin-assets/:path*", permanent: true },
      { source: "/tokenized-iron", destination: "/tokenized-iron-assets", permanent: true },
      { source: "/tokenized-iron/:path*", destination: "/tokenized-iron-assets/:path*", permanent: true },
      { source: "/tokenized-samarium", destination: "/tokenized-samarium-asset", permanent: true },
      { source: "/tokenized-samarium/:path*", destination: "/tokenized-samarium-asset/:path*", permanent: true },
      { source: "/tokenized-thulium", destination: "/tokenized-thulium-asset", permanent: true },
      { source: "/tokenized-thulium/:path*", destination: "/tokenized-thulium-asset/:path*", permanent: true },
      { source: "/tokenized-europium", destination: "/tokenized-europium-asset", permanent: true },
      { source: "/tokenized-europium/:path*", destination: "/tokenized-europium-asset/:path*", permanent: true },
      { source: "/tokenized-holmium", destination: "/tokenized-holmium-asset", permanent: true },
      { source: "/tokenized-holmium/:path*", destination: "/tokenized-holmium-asset/:path*", permanent: true },
      { source: "/tokenized-neodymium", destination: "/tokenized-neodymium-asset", permanent: true },
      { source: "/tokenized-neodymium/:path*", destination: "/tokenized-neodymium-asset/:path*", permanent: true },
      { source: "/tokenized-scandium", destination: "/tokenized-scandium-asset", permanent: true },
      { source: "/tokenized-scandium/:path*", destination: "/tokenized-scandium-asset/:path*", permanent: true },
      { source: "/tokenized-lanthanum", destination: "/tokenized-lanthanum-asset", permanent: true },
      { source: "/tokenized-lanthanum/:path*", destination: "/tokenized-lanthanum-asset/:path*", permanent: true },
      { source: "/tokenized-yttrium", destination: "/tokenized-yttrium-asset", permanent: true },
      { source: "/tokenized-yttrium/:path*", destination: "/tokenized-yttrium-asset/:path*", permanent: true },
      { source: "/tokenized-dysprosium", destination: "/tokenized-dysprosium-asset", permanent: true },
      { source: "/tokenized-dysprosium/:path*", destination: "/tokenized-dysprosium-asset/:path*", permanent: true },
      { source: "/tokenized-ytterbium", destination: "/tokenized-ytterbium-asset", permanent: true },
      { source: "/tokenized-ytterbium/:path*", destination: "/tokenized-ytterbium-asset/:path*", permanent: true },
      { source: "/tokenized-praseodymium", destination: "/tokenized-praseodymium-asset", permanent: true },
      { source: "/tokenized-praseodymium/:path*", destination: "/tokenized-praseodymium-asset/:path*", permanent: true },
      { source: "/tokenized-lutetium", destination: "/tokenized-lutetium-asset", permanent: true },
      { source: "/tokenized-lutetium/:path*", destination: "/tokenized-lutetium-asset/:path*", permanent: true },
      { source: "/tokenized-erbium", destination: "/tokenized-erbium-asset", permanent: true },
      { source: "/tokenized-erbium/:path*", destination: "/tokenized-erbium-asset/:path*", permanent: true },
      { source: "/tokenized-terbium", destination: "/tokenized-terbium-asset", permanent: true },
      { source: "/tokenized-terbium/:path*", destination: "/tokenized-terbium-asset/:path*", permanent: true },
      { source: "/tokenized-gadolinium", destination: "/tokenized-gadolinium-asset", permanent: true },
      { source: "/tokenized-gadolinium/:path*", destination: "/tokenized-gadolinium-asset/:path*", permanent: true },
      { source: "/tokenized-cerium", destination: "/tokenized-cerium-asset", permanent: true },
      { source: "/tokenized-cerium/:path*", destination: "/tokenized-cerium-asset/:path*", permanent: true },
      { source: "/tokenized-promethium", destination: "/tokenized-promethium-asset", permanent: true },
      { source: "/tokenized-promethium/:path*", destination: "/tokenized-promethium-asset/:path*", permanent: true },
    ];
  },
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "framerusercontent.com",
      },
      {
        protocol: "https",
        hostname: "res.cloudinary.com",
      },
      {
        protocol: "https",
        hostname: "blog.totofinance.co",
      },
    ],
  },
};

export default nextConfig;
